{
 "title": "ARARE Dashboard",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Datetime", "query": "SHOW DIAGNOSTICS" }
  ]
 },
 "panels": [
  {
   "title": "Cardano Last Block Epoch",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "cardano_node_metrics_epoch_int", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Cardano Last Block Slot",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 9, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_slotInEpoch_int{job=\"producer-ada-1_cardano_node\"}",
     "legendFormat": "Slot in Epoch"
    },
    {
     "expr": "432000 - cardano_node_metrics_slotInEpoch_int{job=\"producer-ada-1_cardano_node\"}",
     "legendFormat": "Slot left"
    }
   ]
  },
  {
   "title": "Time to next Epoch",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "432000 - cardano_node_metrics_slotInEpoch_int{job=\"producer-ada-1_cardano_node\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "clocks" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by(instance)(time() - node_boot_time_seconds)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Epoch %",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 9, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 - (432000 - cardano_node_metrics_slotInEpoch_int{job=\"producer-ada-1_cardano_node\"}) / 432000 * 100",
     "legendFormat": "{{none}}"
    }
   ]
  },
  {
   "title": "Time to next Epoch",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "432000 - cardano_node_metrics_slotInEpoch_int{job=\"producer-ada-1_cardano_node\"}"
    }
   ]
  },
  {
   "title": "Epoch Dates",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(time()*1000 ) - (cardano_node_metrics_slotInEpoch_int{job=\"producer-ada-1_cardano_node\"} * 1000) +((432000*1000)*1)",
     "legendFormat": "Next Epoch"
    },
    {
     "expr": "(time()*1000 ) - (cardano_node_metrics_slotInEpoch_int{job=\"producer-ada-1_cardano_node\"} * 1000) +((432000*1000)*2)",
     "legendFormat": "Epoch +2"
    },
    {
     "expr": "(time()*1000 ) - (cardano_node_metrics_slotInEpoch_int{job=\"producer-ada-1_cardano_node\"} * 1000) + ((432000*1000)*3)",
     "legendFormat": "Epoch +3"
    },
    {
     "expr": "(time()*1000 ) - (cardano_node_metrics_slotInEpoch_int{job=\"producer-ada-1_cardano_node\"} * 1000) +((432000*1000)*4)",
     "legendFormat": "Epoch +4"
    },
    {
     "expr": "(time()*1000 ) - (cardano_node_metrics_slotInEpoch_int{job=\"producer-ada-1_cardano_node\"} * 1000) +((432000*1000)*5)",
     "legendFormat": "Epoch +5"
    }
   ]
  },
  {
   "title": "Peers - connected",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_connectedPeers_int",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by(instance)(irate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)"
    }
   ]
  },
  {
   "title": "System health",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(instance)(irate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "CPU"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes / (node_memory_MemTotal_bytes)))* 100",
     "legendFormat": "Memory"
    },
    {
     "expr": "(1 - (node_memory_SwapFree_bytes / node_memory_SwapTotal_bytes)) * 100",
     "legendFormat": "SWAP"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\"})",
     "legendFormat": "Disk"
    }
   ]
  },
  {
   "title": "Active Stake",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "adapools_active_stake / 1000000"
    }
   ]
  },
  {
   "title": "Deligators",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "adapools_delegators" }
   ]
  },
  {
   "title": "Pool Rank",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "adapools_rank" }
   ]
  },
  {
   "title": "Live Stake",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "adapools_total_stake / 1000000" }
   ]
  },
  {
   "title": "Node Memory Available (%)",
   "type": "graph",
   "description": "Counts memory that is free as well as reclaimable from caches and buffers",
   "gridPos": { "h": 8, "w": 9, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{alias!~\"monitoring.*\"} / node_memory_MemTotal_bytes{alias!~\"monitoring.*\"} * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "MempoolTx",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_txsInMempool_int"
    }
   ]
  },
  {
   "title": "Keys Rotation in",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "Days" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_remainingKESPeriods_int"
    }
   ]
  },
  {
   "title": "Time to end of Epoch",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(432000 - cardano_node_metrics_slotInEpoch_int{job=\"producer-ada-1_cardano_node\"})"
    }
   ]
  },
  {
   "title": "Slot missed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 8, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cardano_node_metrics_slotsMissedNum_int[1m])*60",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cardano Chain Density",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 26 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_density_real * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ROTATION DATE",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "((time()) - (rate(cardano_node_metrics_slotInEpoch_int{job=\"producer-ada-1_cardano_node\"}[10m])) + (((cardano_node_metrics_remainingKESPeriods_int-1) * 86400) * 1.5) + 119062) * 1000"
    }
   ]
  },
  {
   "title": "Blocks",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_Forge_adopted_int +2",
     "legendFormat": "SKY_Core"
    }
   ]
  },
  {
   "title": "Cardano Last Block Height",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 34 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_blockNum_int",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "cardano_node_metrics_ChainDB_blockNum_int",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "cardano_byron_proxy_ChainDB_blockNum_int",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Block sync speed (blocks / min)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cardano_node_metrics_blockNum_int[150s])*60",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "rate(cardano_node_metrics_ChainDB_blockNum_int[150s])*60",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Rejected blocks since last restart",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_forged_int - cardano_node_metrics_adopted_int",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "TX processed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_txsProcessedNum_int",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 42 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "node_filefd_allocated", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Time Sync",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "node_timex_maxerror_seconds * 1000"
    }
   ]
  },
  {
   "title": "MempoolBytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_mempoolBytes_int",
     "legendFormat": "mempoolBytes"
    }
   ]
  },
  {
   "title": "Cluster Aggregate Data Transfer, 1 hr Rolling Window",
   "type": "graph",
   "description": "/",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 50 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by(instance)(rate(node_network_receive_bytes_total{alias!~\"monitoring.*\",device!~\"lo\"}[1h])) * 3600",
     "legendFormat": "1h Cluster Data Received, bytes {{instance}}"
    },
    {
     "expr": "sum by(instance)(rate(node_network_transmit_bytes_total{alias!~\"monitoring.*\",device!~\"lo\"}[1h])) * 3600",
     "legendFormat": "1h Cluster Data Transmitted, bytes {{instance}}"
    }
   ]
  },
  {
   "title": "Node RSS (allocated memory in RAM, in MB)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(cardano_node_metrics_Stat_rss_int*4096)/(1024*1026)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Cardano Slot Height",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_slotNum_int",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node max \"residency\" (amount of live data, MBytes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rts_gc_max_bytes_used/(1024*1024)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Slot leading share (% of slots led)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(cardano_node_metrics_Forge_node_is_leader_int[710s])/rate(cardano_node_metrics_Forge_forge_about_to_lead_int[710s])",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "sum(rate(cardano_node_metrics_Forge_node_is_leader_int[710s])/rate(cardano_node_metrics_Forge_forge_about_to_lead_int[710s]))",
     "legendFormat": "Total led slots"
    }
   ]
  },
  {
   "title": "Slot length",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 66 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "1/rate(cardano_node_metrics_Forge_forge_about_to_lead_int[710s])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node Memory Free (%)",
   "type": "graph",
   "description": "Counts memory that is free as well as reclaimable from caches and buffers",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 66 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{alias!~\"monitoring.*\"} / node_memory_MemTotal_bytes{alias!~\"monitoring.*\"} * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cardano Service Restarts Per Hour",
   "type": "graph",
   "description": "Shows how many times cardano related services have been restarted within a 1 hour lookback window",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "round(increase(node_systemd_unit_state{name=~\"cardano.*|byron.*|explorer.*\",state=\"active\"}[1h:10s])) > 0",
     "legendFormat": "{{alias}}-{{name}}"
    }
   ]
  },
  {
   "title": "Cluster Aggregate Bandwidth (bps)",
   "type": "graph",
   "description": "20 second rolling time average",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 74 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{alias!~\"monitoring.*\",device!~\"lo\"}[20s])) * 8",
     "legendFormat": "Aggregate cluster ingress (received)"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{alias!~\"monitoring.*\",device!~\"lo\"}[20s]) * -8)",
     "legendFormat": "Aggregate cluster egress (transmit)"
    }
   ]
  },
  {
   "title": "Node Bandwidth (bps)",
   "type": "graph",
   "description": "20 second rolling time average",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 74 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{alias!~\"monitoring.*\",device!~\"lo\"}[20s]) * 8",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{alias!~\"monitoring.*\",device!~\"lo\"}[20s]) * -8",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Node peak memory allocated (from OS, in MBytes)",
   "type": "graph",
   "description": "Counts only memory that is physically free",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rts_gc_peak_megabytes_allocated",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node Uptime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 82 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(time()-node_boot_time_seconds)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node current \"residency\" (amount of live data, MBytes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 90 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rts_gc_current_bytes_used/(1024*1024)",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}